project1/project1/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("project1app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

project1/project1app/urls.py
from django.urls import path
from . import views
app_name='project1app'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

project1/project1app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField('')
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

project1/project1app/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

project1/project1app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movie=Movie.objects.all()
    contents={
        'movie_list':movie
    }
    return render(request,'index.html',contents)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})

def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add_movie.html")

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form': form, 'movie': movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

project1/templates/add_movie.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <br>
    <input type="text" name="name" placeholder="Enter movie name"><br>
    <br>
    <input type="text" name="desc" placeholder="Enter movie description"><br>
    <br>
    <input type="text" name="year" placeholder="Enter year of release"><br>
    <br>
    <input type="file" name="img"><br>
    <br>
    <input type="submit"><br>
</form>
{% endblock %}

project1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Catalog
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

project1/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    Are you sure,You want to delete this movie?
    <input type="submit">
</form>
{% endblock %}

project1/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<h2>{{movie.name}}</h2> <img src="{{movie.img.url}}" width="150" height="200"><br>
{{movie.desc}}<br>
<br>
Year of release:{{movie.year}}<br>
<a class="btn btn-primary" href="{% url 'project1app:update' movie.id %}">Edit</a>
<a class="btn btn-danger" href="{% url 'project1app:delete' movie.id %}">Delete</a>
{% endblock %}

project1/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

project1/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 16rem;">
  <img class="Card-image-top" src="{{i.img.url}}" alt="..." height="300" >
  <div class="card-body">
    <h6 class="card-title">{{i.name}}</h6>
    <a href="{% url 'project1app:detail' i.id %}" class="btn btn-primary">Detail</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
    <br><a class="btn btn-danger"  href="{% url 'project1app:add_movie' %}">Add New</a>
</div>

{% endblock %}